name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        submodules: recursive
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Install pipenv
      run: pip install pipenv --upgrade
    - name: Install packages
      run: pipenv sync --dev
    - name: Migrate
      run: pipenv run python manage.py migrate
    - name: Check python codestyle
      run: pipenv run flake8
    - name: Test
      run: pipenv run python manage.py test
    - name: Check django deployment settings
      run: pipenv run python manage.py check --deploy
